DROP DATABASE IF EXISTS chat;
CREATE DATABASE chat;

USE chat;

CREATE TABLE Users (
  id int AUTO_INCREMENT,
  username varchar(255),
  PRIMARY KEY (id)
);
    
CREATE TABLE Messages (
  id INTEGER AUTO_INCREMENT,
  text VARCHAR(255),
  createdAt DATE,
  userID INTEGER,
  roomID INTEGER,
  PRIMARY KEY (id)
);
    
CREATE TABLE Friends (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  userID INTEGER,
  friendID INTEGER
);
    
CREATE TABLE Rooms (
  id INTEGER AUTO_INCREMENT,
  roomname VARCHAR(255),
  PRIMARY KEY (id)
);

ALTER TABLE Messages ADD FOREIGN KEY (userID) REFERENCES Users (id);
ALTER TABLE Messages ADD FOREIGN KEY (roomID) REFERENCES Rooms (id);
ALTER TABLE Friends ADD FOREIGN KEY (userID) REFERENCES Users (id);
ALTER TABLE Friends ADD FOREIGN KEY (friendID) REFERENCES Users (id);